name: Run e2e Tests Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t test-project-qa .

      - name: Run with env vars
        run: |
          docker run --rm $(env | sed 's/^/-e /') test-project-qa
        env:
          DEMOQA: ${{ secrets.DEMOQA }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
